### ISSUE TITLE
Es wird nicht mehr Aktualisiert.

### ISSUE THREAD

**Issue by amnesia106** [Jacubeit/Bitcoin-MoneyMoney#4]
```
10:54:55  The server responded with the error message: Service Unavailable. Retrying...
          Sending: GET https://blockexplorer.com/api/addr/1Mixk75baGpXQH6qVxyzDNqjQcg2Kk1vQG/balance
10:54:56  HTTPS response: Service Unavailable
          Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal.
```

**Comment by zealot128** [comment]
The issue is with the information provider, Blockexplorer, which has a very unstable server api. Sometimes, after refreshing multiple times, it works, but most times there is 502 or similar.

**Comment by zealot128** [comment]
There is also no visible support for MoneyMoney Extension Error handling, so there is nothing , this extension can do (Retry etc).

BUT, changing the API could work; This API is fast and could be easy drop in:

https://chain.so/api/v2/get_address_balance/BTC/1Mixk75baGpXQH6qVxyzDNqjQcg2Kk1vQG/

**Comment by mrh-line** [comment]
When setting the HTTP header field "Accept" to "application/json", MoneyMoney will forward the HTTP error to the extension, allowing it to retry or to handle the error gracefully. (cf. keyword "JSON-basierte REST-APIs" in documentation).
